// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlogBuilder.Models;

public partial class BLOG_USER
{
    [Key]
    public int USERID { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string USERNAME { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string PASSWORD { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string EMAIL { get; set; }

    [InverseProperty("USER")]
    public virtual ICollection<BLOG> BLOG { get; set; } = new List<BLOG>();
}