// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlogBuilder.Models;

public partial class BLOG
{
    [Key]
    public int BLOGID { get; set; }

    public int? USERID { get; set; }

    [Required]
    public string BLOG_NAME { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string TOPIC_NAME { get; set; }

    [Required]
    public string BLOG_CONTENT { get; set; }

    public byte[] IMAGE_DATA { get; set; }

    public DateOnly? MODIFIED_DATE { get; set; }

    public bool isUpdated { get; set; }

    [InverseProperty("BLOG")]
    public virtual ICollection<BLOG_COMMENTS> BLOG_COMMENTS { get; set; } = new List<BLOG_COMMENTS>();

    [ForeignKey("USERID")]
    [InverseProperty("BLOG")]
    public virtual BLOG_USER USER { get; set; }
}