// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BlogBuilder.Models;

public partial class BLOG_PROJECTContext : DbContext
{
    public BLOG_PROJECTContext(DbContextOptions<BLOG_PROJECTContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BLOG> BLOG { get; set; }

    public virtual DbSet<BLOG_USER> BLOG_USER { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BLOG>(entity =>
        {
            entity.HasKey(e => e.BLOGID).HasName("PK_BLOG_BLOGID");

            entity.Property(e => e.MODIFIED_DATE).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.USER).WithMany(p => p.BLOG).HasConstraintName("FK_BLOG_USERID");
        });

        modelBuilder.Entity<BLOG_USER>(entity =>
        {
            entity.HasKey(e => e.USERID).HasName("PK_BLOG_USER_USERID");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}