// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlogBuilder.Models;

public partial class BLOG_COMMENTS
{
    [Key]
    public int COMMENTID { get; set; }

    public int USERID { get; set; }

    public int BLOGID { get; set; }

    public string COMMENT { get; set; }

    [ForeignKey("BLOGID")]
    [InverseProperty("BLOG_COMMENTS")]
    public virtual BLOG BLOG { get; set; }

    [ForeignKey("USERID")]
    [InverseProperty("BLOG_COMMENTS")]
    public virtual BLOG_USER USER { get; set; }
}